### ISSUE TITLE
Add Blog Post for 0.13.0 Release

### ISSUE THREAD

**Issue by Doppp** [haxegon/haxegon.com#9]
Should update the blog with the 0.13.0 details. Basically copy and paste the stuff [here](https://github.com/haxegon/haxegon/releases/tag/v0.13.0). I'm in Jakarta now so will do it when I return.

@TerryCavanagh How come there is a `v` in front of the 0.13.0 release? My OCD is tingling because the other releases don't have them. 😆 😭

**Comment by TerryCavanagh** [comment]
That would be great, thank you!

ahh I'm not sure why I added a `v` in front, sorry 😅 Picked up a habit somewhere from Dicey Dungeons, I think!

**Comment by Doppp** [comment]
@TerryCavanagh Would you like me to retroactively add the previous releases as blog posts too or just start with 0.13.0?

**Comment by TerryCavanagh** [comment]
Actually yeah, that makes sense! There's obviously no rush though (I haven't figured out the haxegon.com Jekyll setup yet, but when I do I'm happy to do this all myself)

**Comment by Doppp** [comment]
Done!

**Comment by TerryCavanagh** [comment]
Thank you! This looks great :)
